spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service
                fallbackuri: forward:/paymentServiceFallBack
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/yellowrestaurant/api/v1/user/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000

server:
  port: 8989